import './sass/main.scss'
import 'jquery/dist/jquery.js'
import 'bootstrap'
import 'bootstrap-select/dist/js/bootstrap-select.js'
import 'bootstrap-select/dist/js/i18n/defaults-pt_BR.js'
import 'swiper'
import 'animejs'
import './js/scripts.js'
